spring.application.name=IdentityService

server.port=5001

spring.datasource.url=jdbc:postgresql://localhost:5432/identity_db
spring.datasource.username=admin
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=



jwt.secret=${JWT_SECRET}
jwt.access-expiration=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
jwt.refresh-expiration=${JWT_REFRESH_TOKEN_EXPIRATION_DAYS}
jwt.issuer=${JWT_ISSUER}
jwt.audience=${JWT_AUDIENCE}