spring.application.name=NotificationService
server.port=5002

# =========================
# DATABASE (POSTGRESQL)
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/notification_db
spring.datasource.username=admin
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================
# REDIS
# =========================
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=

# =========================
# KAFKA
# =========================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service-group
spring.kafka.consumer.auto-offset-reset=earliest
kafka.consumer.enabled=true

# =========================
# SMTP (MAIL)
# =========================
spring.mail.host=${SMTP_HOST:smtp.gmail.com}
spring.mail.port=${SMTP_PORT:587}

spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.from=${SMTP_FROM_EMAIL}